name: SocialRating
version: '1.2.0'
main: org.bakinu.socialRating.SocialRating
api-version: '1.21'
depend: [PlaceholderAPI]
commands:
  getrating:
    permission: socialrating.command.getrating
    description: Gets player rating
  setrating:
    permission: socialrating.command.setrating
    description: Sets player rating
  toprating:
    permission: socialrating.command.toprating
    description: Sends highest ratings on server
  srreload:
    permission: socialrating.command.srreload
permissions:
  socialrating.command.getrating:
    default: true
  socialrating.command.srreload:
    default: op
  socialrating.command.setrating:
    default: op
  socialrating.command.toprating:
    default: true